version: '3.8'

services:
  frontend:
    build:
        context: ../React_frontend/
    ports:
        - "5173:5173"
  
  backend:
    build:
       context: ../backend/
    ports:
       - "8000:8000"

networks:
  default:
   driver: bridge
    